import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Navbar from "@/components/Navbar";
import { Plane, MapPin, DollarSign, Calendar } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import heroImage from "@/assets/india-hero.jpg";

const Index = () => {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      setUser(session?.user ?? null);
    });

    return () => subscription.unsubscribe();
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-secondary/20">
      <Navbar user={user} />
      
      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-accent/10" />
        <div className="container mx-auto relative z-10">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div className="space-y-6 animate-fade-in">
              <h1 className="text-5xl md:text-6xl font-bold leading-tight">
                Plan your next{" "}
                <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                  Indian adventure
                </span>
              </h1>
              <p className="text-xl text-muted-foreground">
                Smart, easy, and affordable trip planning powered by AI 🇮🇳
              </p>
              <div className="flex flex-wrap gap-4">
                <Link to={user ? "/plan" : "/auth"}>
                  <Button size="lg" className="bg-gradient-to-r from-primary to-accent text-white hover:opacity-90 text-lg px-8">
                    Start Planning
                  </Button>
                </Link>
                <Link to="/explore">
                  <Button size="lg" variant="outline" className="text-lg px-8">
                    Explore India
                  </Button>
                </Link>
              </div>
            </div>
            <div className="animate-slide-up">
              <img 
                src={heroImage} 
                alt="Beautiful Indian destinations including Taj Mahal, Kerala backwaters, and Himalayan mountains" 
                className="rounded-2xl shadow-2xl w-full object-cover"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 bg-background/50">
        <div className="container mx-auto">
          <h2 className="text-4xl font-bold text-center mb-12">
            Why Choose <span className="text-primary">EasyTravel India</span>?
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            <Card className="p-6 space-y-4 hover:shadow-lg transition-shadow animate-fade-in">
              <div className="w-12 h-12 bg-gradient-to-br from-primary to-primary-glow rounded-lg flex items-center justify-center">
                <Plane className="h-6 w-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold">AI-Powered Planning</h3>
              <p className="text-muted-foreground">
                Get personalized itineraries generated by advanced AI for your perfect Indian trip
              </p>
            </Card>

            <Card className="p-6 space-y-4 hover:shadow-lg transition-shadow animate-fade-in" style={{ animationDelay: "0.1s" }}>
              <div className="w-12 h-12 bg-gradient-to-br from-accent to-secondary rounded-lg flex items-center justify-center">
                <MapPin className="h-6 w-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold">Top Destinations</h3>
              <p className="text-muted-foreground">
                Explore Delhi, Jaipur, Goa, Kerala, Manali, and many more amazing places
              </p>
            </Card>

            <Card className="p-6 space-y-4 hover:shadow-lg transition-shadow animate-fade-in" style={{ animationDelay: "0.2s" }}>
              <div className="w-12 h-12 bg-gradient-to-br from-primary to-accent rounded-lg flex items-center justify-center">
                <DollarSign className="h-6 w-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold">Budget Optimizer</h3>
              <p className="text-muted-foreground">
                Smart budget allocation: 40% transport, 35% stay, 15% food, 10% activities
              </p>
            </Card>

            <Card className="p-6 space-y-4 hover:shadow-lg transition-shadow animate-fade-in" style={{ animationDelay: "0.3s" }}>
              <div className="w-12 h-12 bg-gradient-to-br from-accent to-primary rounded-lg flex items-center justify-center">
                <Calendar className="h-6 w-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold">Save & Track Trips</h3>
              <p className="text-muted-foreground">
                Save your trips, track budgets, and access itineraries anytime from your dashboard
              </p>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto">
          <Card className="p-12 bg-gradient-to-r from-primary to-accent text-white text-center space-y-6">
            <h2 className="text-4xl font-bold">Ready to Explore India?</h2>
            <p className="text-xl opacity-90">
              Start planning your dream vacation today with AI-powered itineraries
            </p>
            <Link to={user ? "/plan" : "/auth"}>
              <Button size="lg" variant="secondary" className="text-lg px-8">
                Get Started Now
              </Button>
            </Link>
          </Card>
        </div>
      </section>
    </div>
  );
};

export default Index;
